---
- name: Ensure nginx is installed
  become: true
  ansible.builtin.package:
    name: nginx
    state: present

- name: Copy files/https.conf file to /etc/nginx/conf.d/https.conf
  ansible.builtin.copy:
    src: files/https.conf
    dest: /etc/nginx/conf.d/https.conf
    mode: '0644'

- name: Ensure nginx is started at boot
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

- name: Ensure nginx is installed
  become: true
  ansible.builtin.package:
    name: nginx
    state: present

- name: Copy files/https.conf file to /etc/nginx/conf.d/https.conf
  ansible.builtin.copy:
    src: files/https.conf
    dest: /etc/nginx/conf.d/https.conf
    mode: '0644'
  register: result_https_conf

- name: Ensure the nginx configuration is updated for example.internal
  become: true
  ansible.builtin.copy:
    src: files/example.internal.conf
    dest: /etc/nginx/conf.d/example.internal.conf
    mode: '0644'
  register: result_internal_conf

- name: Create directory structure
  ansible.builtin.file:
    path: /var/www/example.internal/html/
    state: directory
    setype: httpd_sys_content_t
    mode: '0644'

- name: Copy files/index.html to /var/www/example.internal/html/index.html
  become: true
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/example.internal/html/index.html
    setype: httpd_sys_content_t
    mode: '0644'

- name: Deploy templated nginx config for example.internal
  become: true
  ansible.builtin.template:
    src: templates/example.internal.conf.j2
    dest: /etc/nginx/conf.d/example.internal.conf
    mode: '0644'
  notify: Reload nginx to apply new template conf

- name: Create directory structure
  ansible.builtin.file:
    path: /var/www/example.internal/html/
    state: directory
    setype: httpd_sys_content_t
    mode: '0644'

- name: Add users with their groups
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    append: true
    state: present
    password: "{{ item.password }}"
  loop:
    - {name: "alovelace", groups: "wheel,video,audio", password: "$6$rounds=656000$salt1$kT5FYBCPAO4ii3Yx8zFCM8gB3cLufVWPRBnXVDtPweZdkjyWr/px4J7FnVV7SAHbKOWeXZtTENrq7bdIG5tUr0"}
    - {name: "aturing", groups: "tape", password: "$6$rounds=656000$salt2$alTmmNCl9o1B7DtkO7IIFlSNjuiDNB17cm.xYk2A71uqVQ.2UJIJoLJrOPFCIliHX/xE2x2tJOEhAWvU8Mi4h/"}
    - {name: "edijkstra", groups: "tcpdump", password: "$6$rounds=656000$salt3$NFBVhdSb3bNdoIm8jVnwbMjEINOHWfeo5fJLjStLD0.xK.kfOKpCevjG17d2FpokXdZ83EvFfKfiSwkPH08F8."}
    - {name: "ghopper", groups: "wheel,audio", password: "$6$rounds=656000$salt4$yLL4idgjdVc4jyFrIuRrYJ8E4itY7tAsaUrwEO09bEMdAT0xhXvkl4Z6ghXKRxSNQMhS7W2VUXlwztrmJ3Lpx0"}
