---
- name: Copy all the '\*.md' files to 'deploy' user's directory
  hosts: db
  become: true
  tasks:
    - name: Copy each file over that matches the given pattern
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/deploy
        owner: deploy
        group: deploy
        mode: '0644'
      with_fileglob:
        - 'files/*.md'
